```yaml
name: "Dr. Mujeeb Ahmad"

avatar: "images/profile.jpg"

bio: "Postdoctoral Research Fellow at the Institute of Physics, Polish Academy of Sciences. Research interests include superconducting quantum devices, quantum transport, topological materials, and thermoelectric phenomena."

location: "Warsaw, Poland"

email: "mahmad@magtop.ifpan.edu.pl"

googlescholar: "https://scholar.google.co.in/citations?user=Hl7iOHYAAAAJ&hl=en"

orcid: "https://orcid.org/0000-0003-4996-3783"

linkedin: "mujeeb-ahmad-ph-d-b7a47956"

researchgate: "Mujeeb-Ahmad-2"

github: "Mujeebhmad"
```
